# Generated by Django 4.2.14 on 2024-08-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_kategori_movie_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Kategori',
            new_name='kategori',
        ),
    ]
